# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa429159e4230b75767365765ca6d453b9a52113bfbdd498b6a5aea6617045c5155c4dda7a87df40e68f3a3e679bd522ea24e470bd80bd8dc8f08e76a23f4c30

test:
  secret_key_base: 895b9be81c54657b8a6a7730a151ad7df6cfc69ff6b166fde5b833f399fc1780b0d1ef5f67de15f074cb0485cc0c7238f0e5b9bab0583ae6e731c088731445cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
